In [1]:
import numpy as np

# Ejercicios

1.  Genera un *array* bidimensional de 4 x 3 con valores aleatorios enteros entre el 34 y el 98. Una vez creado cada array comprueba las dimensiones y los tipos de datos que tenemos en el array. 

2. Crea dos *arrays* (unidimensional, bidimensional) usando el método `np.array()`. 

    Las listas para crear los *arrays* son las siguientes

    ```python
    lista1 = [34,56,71,98, 10]
    lista2 = [[23,45,89, 56], [12,43,82,44]]
    ```

    **Bonus** Haz una pequeña descripción de cada *array* usando los métodos de exploración de *arrays* que hemos aprendido.


In [14]:
# Generar el array bidimensional de 4 x 3 con valores aleatorios enteros entre 34 y 98
array_4x3 = np.random.randint(34, 99, size=(4, 3))

# Comprobar las dimensiones del array
dimensiones = array_4x3.shape

# Comprobar el tipo de datos del array
tipo_datos = array_4x3.dtype

print("Array bidimensional de 4x3:")
print(array_4x3)
print("\nDimensiones del array:", dimensiones)
print("Tipo de datos del array:", tipo_datos)


Array bidimensional de 4x3:
[[68 44 81]
 [93 94 70]
 [40 69 69]
 [72 42 75]]

Dimensiones del array: (4, 3)
Tipo de datos del array: int64


In [15]:
lista1 = [34, 56, 71, 98, 10]
lista2 = [[23, 45, 89, 56], [12, 43, 82, 44]]

# Crear los arrays
array_unidimensional = np.array(lista1)
array_bidimensional = np.array(lista2)

# Descripción de los arrays
print("Array unidimensional:")
print(array_unidimensional)
print("Dimensiones:", array_unidimensional.shape)
print("Tipo de datos:", array_unidimensional.dtype)
print("Número de elementos:", array_unidimensional.size)

print("\nArray bidimensional:")
print(array_bidimensional)
print("Dimensiones:", array_bidimensional.shape)
print("Tipo de datos:", array_bidimensional.dtype)
print("Número de elementos:", array_bidimensional.size)

Array unidimensional:
[34 56 71 98 10]
Dimensiones: (5,)
Tipo de datos: int64
Número de elementos: 5

Array bidimensional:
[[23 45 89 56]
 [12 43 82 44]]
Dimensiones: (2, 4)
Tipo de datos: int64
Número de elementos: 8


# Ejercicios


1. Crea un *array* unidimensional con 50 elementos con el método que prefieras y extrae: 

    - El primer elemento.


    - Lo elementos que están en posición impar.


    - Los cuatro primeros elementos.


    - Los últimos tres elementos.


    - Los elementos entre el 4 y el 8 (incluido). 

2. Crea un *array* de dos dimensiones de 4 x 5 con el método que prefieras y extrae:

    - La primera fila y todas las columnas.


    - Todas las filas pares.


    - La primera columna y todas las filas.


In [17]:
# Crear un array unidimensional con 50 elementos (valores aleatorios entre 0 y 100)
array_1d = np.random.randint(0, 101, size=50)

# Extraer el primer elemento
primer_elemento = array_1d[0]

# Extraer los elementos en posición impar
elementos_posicion_impar = array_1d[1::2]

# Extraer los cuatro primeros elementos
cuatro_primeros_elementos = array_1d[:4]

# Extraer los últimos tres elementos
ultimos_tres_elementos = array_1d[-3:]

# Extraer los elementos entre el 4 y el 8 (incluido)
elementos_4_al_8 = array_1d[4:9]

print("Array unidimensional con 50 elementos:")
print(array_1d)
print("\nPrimer elemento:", primer_elemento)
print("Elementos en posición impar:", elementos_posicion_impar)
print("Cuatro primeros elementos:", cuatro_primeros_elementos)
print("Últimos tres elementos:", ultimos_tres_elementos)
print("Elementos entre el 4 y el 8 (incluido):", elementos_4_al_8)


Array unidimensional con 50 elementos:
[ 76  34  52  45  22  68  54  20  59  60  76  83  45  35  63  55  86  91
   2  59  26  11  38  88  37  81  68  37  15  92  13  75  73   9  51  38
  22   6  37  24  36  26  14  14  94  19  71 100   1  69]

Primer elemento: 76
Elementos en posición impar: [ 34  45  68  20  60  83  35  55  91  59  11  88  81  37  92  75   9  38
   6  24  26  14  19 100  69]
Cuatro primeros elementos: [76 34 52 45]
Últimos tres elementos: [100   1  69]
Elementos entre el 4 y el 8 (incluido): [22 68 54 20 59]


In [16]:
# Crear un array bidimensional de 4 x 5 (valores aleatorios entre 0 y 100)
array_2d = np.random.randint(0, 101, size=(4, 5))

# Extraer la primera fila y todas las columnas
primera_fila = array_2d[0, :]

# Extraer todas las filas pares
filas_pares = array_2d[::2, :]

# Extraer la primera columna y todas las filas
primera_columna = array_2d[:, 0]

print("Array bidimensional de 4x5:")
print(array_2d)
print("\nPrimera fila y todas las columnas:", primera_fila)
print("Todas las filas pares:\n", filas_pares)
print("Primera columna y todas las filas:", primera_columna)


Array bidimensional de 4x5:
[[38 58  4 87 80]
 [91 20 89 72 85]
 [29 50 33 74 88]
 [91 78 79 21 42]]

Primera fila y todas las columnas: [38 58  4 87 80]
Todas las filas pares:
 [[38 58  4 87 80]
 [29 50 33 74 88]]
Primera columna y todas las filas: [38 91 29 91]


# Ejercicios


1. Crea un *array* bidimensional con 20 elementos aleatrorios entre 0 y 50 con el método que prefieras y: 

    - Crea una mascara o filtro donde los valores mayores a 30 y menores a 10 se reemplace por "objetivo" y el resto por "no es mi objetivo".


    - Los valores de mi array bidimensional multiplicalos por el escalar 10.


2. Crea un nuevo *array* de dos dimensiones con la misma forma que el anterior y con el método que prefieras y realiz lo siguiente:

    - Suma el primer array con el segundo.


    - Aplicar la potencia para el primer array elevado al segundo.


In [18]:
# Crear un array bidimensional de 4 x 5 con valores aleatorios entre 0 y 50
array_2d = np.random.randint(0, 51, size=(4, 5))

# Crear una máscara o filtro
mascara = np.where((array_2d > 30) | (array_2d < 10), "objetivo", "no es mi objetivo")

# Multiplicar los valores del array bidimensional por el escalar 10
array_multiplicado = array_2d * 10

print("Array bidimensional original de 4x5:")
print(array_2d)
print("\nMáscara o filtro:")
print(mascara)
print("\nArray multiplicado por 10:")
print(array_multiplicado)

Array bidimensional original de 4x5:
[[15 25 43 20 48]
 [27 27 35 26 28]
 [15  1 34 40 19]
 [45 30 20 42 50]]

Máscara o filtro:
[['no es mi objetivo' 'no es mi objetivo' 'objetivo' 'no es mi objetivo'
  'objetivo']
 ['no es mi objetivo' 'no es mi objetivo' 'objetivo' 'no es mi objetivo'
  'no es mi objetivo']
 ['no es mi objetivo' 'objetivo' 'objetivo' 'objetivo'
  'no es mi objetivo']
 ['objetivo' 'no es mi objetivo' 'no es mi objetivo' 'objetivo'
  'objetivo']]

Array multiplicado por 10:
[[150 250 430 200 480]
 [270 270 350 260 280]
 [150  10 340 400 190]
 [450 300 200 420 500]]


In [19]:
# Crear un nuevo array bidimensional de 4 x 5 con valores aleatorios entre 0 y 50
nuevo_array_2d = np.random.randint(0, 51, size=(4, 5))

# Sumar el primer array con el segundo
array_suma = array_2d + nuevo_array_2d

# Aplicar la potencia para el primer array elevado al segundo
array_potencia = np.power(array_2d, nuevo_array_2d)

print("\nNuevo array bidimensional de 4x5:")
print(nuevo_array_2d)
print("\nSuma del primer array con el segundo:")
print(array_suma)
print("\nPrimer array elevado al segundo:")
print(array_potencia)



Nuevo array bidimensional de 4x5:
[[50 16 15 35 28]
 [10 27 42 14  9]
 [ 7 24 17 36 42]
 [25 11 44 37  2]]

Suma del primer array con el segundo:
[[65 41 58 55 76]
 [37 54 77 40 37]
 [22 25 51 76 61]
 [70 41 64 79 52]]

Primer array elevado al segundo:
[[-8195635865568426527  3273344365508751233  6080727033296642243
                     0                    0]
 [     205891132094649 -5278486589563110205 -7103562900152310551
   9169742482168496128       10578455953408]
 [           170859375                    1 -7597915146251272192
                     0 -7921048178808804855]
 [-8319904882144399347    17714700000000000                    0
   8353650230385704960                 2500]]


# Ejercicios


1. En este ejercicio vamos a tratar de usar algunos de los métodos aprendidos. 

    - Crea un *array*, puede ser bidimensional! Eso si, los valores tienen que estar entre 0-100

    - Calcula: 

        - La media de los elementos
        - La media de las columnas y redondéalo a dos decimales
        - El valor máximo de cada fila
        - El valor mínimo de cada fila
        - Hay algun valor que sea mayor que 90 en tu *array* 
        - Donde los podemos encontrar, cuáles son sus índices
        - Ordena el *array* de mayor a menor

    📝 **NOTA** En este ejercicio os hemos pedido algunos de los métodos, pero sentiros libres de practicar otros para ir asentando los conocimientos. 

In [20]:
array = np.random.randint(0, 101, size=(5, 5))
print("Array bidimensional:")
print(array)

Array bidimensional:
[[46 27 20 33  2]
 [22 21 16 74 68]
 [32 27 55 91 98]
 [19 66 80 79 62]
 [80 87 92 43 95]]


1. Media de los Elementos

In [21]:
array = np.random.randint(0, 101, size=(5, 5))
print("Array bidimensional:")
print(array)

Array bidimensional:
[[  3  92  49  52  24]
 [  4  81  76  29  71]
 [ 17  84  75  75  10]
 [ 41  52  25   4  38]
 [ 12  75 100  71  91]]


2. Media de las Columnas (Redondeada a dos Decimales)
Calculamos la media de cada columna y redondeamos a dos decimales.

In [22]:
media_columnas = np.mean(array, axis=0).round(2)
print("\nMedia de las columnas (redondeada a dos decimales):", media_columnas)


Media de las columnas (redondeada a dos decimales): [15.4 76.8 65.  46.2 46.8]


3. Valor Máximo de Cada Fila

In [23]:
max_filas = np.max(array, axis=1)
print("\nValor máximo de cada fila:", max_filas)


Valor máximo de cada fila: [ 92  81  84  52 100]


4. Valor Mínimo de Cada Fila

In [24]:
min_filas = np.min(array, axis=1)
print("\nValor mínimo de cada fila:", min_filas)


Valor mínimo de cada fila: [ 3  4 10  4 12]


5. Valores Mayores que 90

In [25]:
valores_mayores_90 = array > 90
hay_valores_mayores_90 = np.any(valores_mayores_90)
print("\n¿Hay algún valor mayor que 90 en el array?", hay_valores_mayores_90)


¿Hay algún valor mayor que 90 en el array? True


6. Índices de Valores Mayores que 90
Obtenemos los índices de los valores mayores que 90.

In [26]:
indices_mayores_90 = np.argwhere(valores_mayores_90)
print("\nÍndices de valores mayores que 90:")
print(indices_mayores_90)



Índices de valores mayores que 90:
[[0 1]
 [4 2]
 [4 4]]


7. Ordenar el Array de Mayor a Menor
Ordenamos el array de mayor a menor. Dado que el array es bidimensional, primero lo aplanamos, ordenamos y luego lo volvemos a dar forma.

In [27]:
array_ordenado = np.sort(array, axis=None)[::-1].reshape(array.shape)
print("\nArray ordenado de mayor a menor:")
print(array_ordenado)


Array ordenado de mayor a menor:
[[100  92  91  84  81]
 [ 76  75  75  75  71]
 [ 71  52  52  49  41]
 [ 38  29  25  24  17]
 [ 12  10   4   4   3]]


Código Completo

In [28]:
# Crear un array bidimensional de 5 x 5 con valores aleatorios entre 0 y 100
array = np.random.randint(0, 101, size=(5, 5))
print("Array bidimensional:")
print(array)

# Calcular la media de todos los elementos
media_total = np.mean(array)
print("\nMedia de todos los elementos:", media_total)

# Calcular la media de las columnas y redondear a dos decimales
media_columnas = np.mean(array, axis=0).round(2)
print("\nMedia de las columnas (redondeada a dos decimales):", media_columnas)

# Obtener el valor máximo de cada fila
max_filas = np.max(array, axis=1)
print("\nValor máximo de cada fila:", max_filas)

# Obtener el valor mínimo de cada fila
min_filas = np.min(array, axis=1)
print("\nValor mínimo de cada fila:", min_filas)

# Verificar si hay algún valor mayor que 90 en el array
valores_mayores_90 = array > 90
hay_valores_mayores_90 = np.any(valores_mayores_90)
print("\n¿Hay algún valor mayor que 90 en el array?", hay_valores_mayores_90)

# Obtener los índices de los valores mayores que 90
indices_mayores_90 = np.argwhere(valores_mayores_90)
print("\nÍndices de valores mayores que 90:")
print(indices_mayores_90)

# Ordenar el array de mayor a menor
array_ordenado = np.sort(array, axis=None)[::-1].reshape(array.shape)
print("\nArray ordenado de mayor a menor:")
print(array_ordenado)

Array bidimensional:
[[65 57  5 33 60]
 [32 71 40 13 95]
 [14 82 76 55 99]
 [16 80 40 53 30]
 [40 42 72 11 59]]

Media de todos los elementos: 49.6

Media de las columnas (redondeada a dos decimales): [33.4 66.4 46.6 33.  68.6]

Valor máximo de cada fila: [65 95 99 80 72]

Valor mínimo de cada fila: [ 5 13 14 16 11]

¿Hay algún valor mayor que 90 en el array? True

Índices de valores mayores que 90:
[[1 4]
 [2 4]]

Array ordenado de mayor a menor:
[[99 95 82 80 76]
 [72 71 65 60 59]
 [57 55 53 42 40]
 [40 40 33 32 30]
 [16 14 13 11  5]]


In [132]:
chicas  = 'p','f','n'

np.random.choice(chicas)

'n'